name: 'cirr_task7'
type: 'hgf'
dataset_path: 'justram/cirr_task7'
qrels_config: 'qrels'
corpus_config: 'corpus'
query_config: 'query'
split: 'test'
main_metrics: ['map', 'ndcg@10', 'hit_rate@1', 'hit_rate@5', 'hit_rate@10']
distance_metrics: 'cos'
topk: 1000
callbacks: None